---
# tasks file for kubernetes.worker
- name: Configure yum repo for Kubernetes
  yum_repository:
    name: kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey:
      - https://packages.cloud.google.com/yum/doc/yum-key.gpg
      - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    description: "Yum repository for Kubernetes"

- name: Install required packages
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ pkgs }}"

- name: Start and enable kubelet
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: "{{ services }}"
  register: svc_start

- name: Change docker cgroup
  copy:
    dest: "{{ docker_daemon }}"
    src: daemon.json
  when: svc_start.changed
  notify: restart docker

- name: Force handler to execute
  meta: flush_handlers

- name: Copy k8s.conf file to worker
  copy:
    src: k8s.conf
    dest: "{{ kubernetes_config }}"
  register: result

- name: Load settings from all system configuration files
  shell: sysctl --system
  when: result.changed

- name: "Join the worker to master"
  command: "{{ hostvars.Dummy_Host.join_cmd }}"
  when: result.changed
