---
# defaults file for kubernetes.worker

# Packages to be installed for Kubernetes
pkgs:
  - kubelet
  - kubectl
  - kubeadm
  - docker
  - iproute-tc

# Services to be started
services:
  - kubelet
  - docker

# Path for docker configuration directory
docker_daemon: /etc/docker/daemon.json

# Path for sysctl.d configuration directory
kubernetes_config: /etc/sysctl.d/k8s.conf
